# Generated by Django 3.2.5 on 2022-02-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BbsUser',
            fields=[
                ('userId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('userPwd', models.CharField(max_length=50)),
                ('userName', models.CharField(max_length=50)),
            ],
        ),
    ]
